# Configuration du scraper Instagram

username: "${{ secrets.IG_USERNAME }}"  # Nom d'utilisateur Instagram
password: "${{ secrets.IG_PASSWORD }}"  # Mot de passe Instagram

# Liste des profils à scraper
influencers:
  - profile_url: "https://www.instagram.com/instagram/"  # URL du profil Instagram
    num_posts: 10  # Nombre de publications à scraper (10 ici)
  - profile_url: "https://www.instagram.com/nasa/"
    num_posts: 10
  - profile_url: "https://www.instagram.com/toni.kr8s/"
    num_posts: 10
