username: "${{ secrets.IG_USERNAME }}"
password: "${{ secrets.IG_PASSWORD }}"
influencers:
  - profile_url: "https://www.instagram.com/instagram/"
    num_posts: 10
  - profile_url: "https://www.instagram.com/nasa/"
    num_posts: 10
  - profile_url: "https://www.instagram.com/toni.kr8s/"
    num_posts: 10
