name: Generate & Analyze Comments

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to scrape & analyze
        run: python scrape_analyze.py

      - name: Commit and push generated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update data via GitHub Actions"
          git push origin HEAD:${{ github.ref }}
